### ISSUE TITLE
Node 18 support

### ISSUE THREAD

**Issue by MaxLeiter** [ldapjs/node-ldapjs#804]
`yarn test` with Node 18:

```
Suites:   ​53 passed​, ​53 of 54 completed​
Asserts:  ​​​3 failed​, ​2774 passed​, ​of 2777​
```

**Comment by MaxLeiter** [comment]
@jsumners I'm interested in contributing the patch if you (or someone) can provide some guidance on the remaining two tests, I'm a little stuck. https://github.com/ldapjs/node-ldapjs/pull/805

Both are failing with
```
 FAIL ​ test/server.test.js
 ✖ getaddrinfo ENOTFOUND [::]

  test: connection count
  at:
    line: 83
    column: 26
    file: node:dns
    function: GetAddrInfoReqWrap.onlookup
    method: oncomplete
  errno: -3008
  code: ENOTFOUND
  syscall: getaddrinfo
  hostname: "[::]"
  tapCaught: uncaughtException
```

The URLs are being formatted like `ldap://::1:61692`
